#spring.cloud.gcp.sql.database-name=pimdb2-instance
#spring.cloud.gcp.sql.instance-connection-name=inductive-actor-236323:us-central1:pimdb2
### So app starts despite "table already exists" errors.
#spring.sql.init.continue-on-error=true
## Enforces database initialization
#spring.datasource.username=[USERNAME]
#spring.datasource.password=[Password]
#spring.cloud.gcp.project-id=[PROJECT_ID]
#spring.cloud.gcp.credentials.location=[PATH FOR THE JSON FILE]

#spring.datasource.url= jdbc:mysql://us-cdbr-east-06.cleardb.net/heroku_f1b6bc9a762895e?reconnect=true
#spring.datasource.username= bb48ceef1a356d
#spring.datasource.password= 29bb9f08
spring.datasource.url= jdbc:mysql://localhost:3306/bancodopim?useSSL=false
spring.datasource.username= samucatezu
spring.datasource.password= samucatezu


spring.mvc.pathmatch.matching-strategy=ant_path_matcher

spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto= update
spring.jpa.properties.hibernate.format_sql = true
spring.jpa.properties.show-sql= true
spring.jpa.defer-datasource-initialization= true
spring.sql.init.mode=always

# App Properties
bezkoder.app.jwtSecret= bezKoderSecretKey
bezkoder.app.jwtExpirationMs= 86400000
