

#spring.cloud.gcp.sql.database-name=pimdb2-instance
#spring.cloud.gcp.sql.instance-connection-name=inductive-actor-236323:us-central1:pimdb2
### So app starts despite "table already exists" errors.
#spring.sql.init.continue-on-error=true
## Enforces database initialization
#spring.datasource.username=[USERNAME]
#spring.datasource.password=[Password]
#spring.cloud.gcp.project-id=[PROJECT_ID]
#spring.cloud.gcp.credentials.location=[PATH FOR THE JSON FILE]

spring.datasource.url= jdbc:mysql://us-cdbr-east-06.cleardb.net/heroku_ed214a2771caef1?reconnect=true
spring.datasource.username= bd11aa57086cea
spring.datasource.password= 0ba59c2a
#spring.datasource.url= jdbc:mysql://localhost:3306/bancodopim?useSSL=false
#spring.datasource.username= samucatezu
#spring.datasource.password= samucatezu



spring.mvc.pathmatch.matching-strategy=ant_path_matcher

spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto= update
spring.jpa.properties.hibernate.format_sql = true
spring.jpa.properties.show-sql= true
#spring.sql.init.mode=always

# App Properties
bezkoder.app.jwtSecret= bezKoderSecretKey
bezkoder.app.jwtExpirationMs= 86400000
